-d H:\git\TangPrimer20K_LUT-Network\primer25k\LicheeTang25k_SDRAM\sdram\impl\gwsynthesis\sdram.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NES
-cst H:\git\TangPrimer20K_LUT-Network\primer25k\LicheeTang25k_SDRAM\sdram\src\sdram.cst
-cfg H:\git\TangPrimer20K_LUT-Network\primer25k\LicheeTang25k_SDRAM\sdram\impl\pnr\device.cfg
-sdc H:\git\TangPrimer20K_LUT-Network\primer25k\LicheeTang25k_SDRAM\sdram\src\sdram.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
