-d H:\git\Gowin_LUT-Network\mega138K_pro\impl\gwsynthesis\top.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst H:\git\Gowin_LUT-Network\mega138K_pro\src\top.cst
-cfg H:\git\Gowin_LUT-Network\mega138K_pro\impl\pnr\device.cfg
-sdc H:\git\Gowin_LUT-Network\mega138K_pro\src\lcd.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
